### ISSUE TITLE
Option to unpack "allOf" arrays in swagger

### ISSUE THREAD

**Issue by mafrosis** [RonnyPfannschmidt/prance#15] opened 2018-03-27 11:51 UTC
I have a swagger file, from which I would like to extract a JSON schema object for the response to each API endpoint. JSON schema doesn't like the `allOf` magic we've used, so it would be nice if this can be automatically expanded out with an option to `prance`.

I've half hacked together a script to do this for our case, but I feel like this feature ought to sit in prance itself. What do you think? Is this difficult to implement? (I haven't read the source yet)

**Comment by mafrosis** [comment] 2018-03-27 20:42
I had a poke through the code this morning. Very nice! Looks to me like an option to the `ResolvingParser` class which enables another resolver similar to `RefResolver` is the way to go.

On the other hand, you may consider this out of scope for the project?

We're using `allOf` to combine multiple `$ref`s into a single composite response - which I gather isn't an unusual use case.

**Comment by jfinkhaeuser** [comment] 2018-04-04 09:10
Thanks for the feedback - I've been away over Easter, and am now catching up.

Seems like a very reasonable feature request! I'll be back in full swing in the next few days, and should be able to add this.

**Comment by jfinkhaeuser** [comment] 2018-04-04 09:11
Or you can create a PR if you'd like - I happily accept those. But if you can wait, that's also good.

**Comment by jfinkhaeuser** [comment] 2018-04-12 10:41
So. I've now had time to dig into this, and I confess I'm a little confused. `allOf` isn't something you'd want to merge in the specs.

It's supposed to validate an object against all of the referenced specs. In fact, OpenAPI specs say that all items need to be validated independently.

Let's say you have two things you want to validate:
- 'foo' needs to be a string
- 'bar' needs to be an integer

Then merging these in the specs would be simple, and your suggestion makes sense.

However, how about these two validations?
- 'foo' needs to be numeric
- 'foo' needs to be an integer number

Of course the 'merged' spec would simply contain the second of these validations, but you'd actually have to interpret the meaning of the validation in order to merge these sensibly.

It may be that you're using the `allOf` feature in a way where merging is fine, but that's not going to be the general case.

Either that, or I'm seriously misunderstanding what you would like to have here!

**Comment by mafrosis** [comment] 2018-04-13 01:35
@jfinkhaeuser I'm happy to close this issue if you are - I solved the problem for my particular case with a simple wrapper around prance. My code looks like:

```python
def _merge(allOf_list):
    # return a new JSON schema object
    combined_schema = {
        'type': 'object',
        'required': [],
        'properties': {},
    }
    # merge the properties & requireds from each schema in the "allOf"
    for schema in allOf_list:
        combined_schema['properties'].update(schema['properties'])
        combined_schema['required'] += schema.get('required', [])

    return combined_schema


def recursive_merge_allOf(schema_fragment):
    # handle allOf in a list (in definition)
    if type(schema_fragment) is list:
        for i in range(len(schema_fragment)):
            schema_fragment[i] = recursive_merge_allOf(schema_fragment[i])

    # handle allOf in a dict (in body schema)
    elif type(schema_fragment) is dict:
        for k, subschema in schema_fragment.items():
            schema_fragment[k] = recursive_merge_allOf(subschema)

            if k == 'allOf':
                schema_fragment = _merge(subschema)

    return schema_fragment
```

**Comment by jfinkhaeuser** [comment] 2018-04-15 19:38
Cool - it's not as if I don't want to add features you find useful, it's just that this one I am struggling to reconcile with how `allOf` seems to be documented.

**Comment by tommyjcarpenter** [comment] 2022-09-27 14:34
I hit this same exact problem today too - and needed @mafrosis `def _merge(allOf_list):` function above

the problem is, now the code doesnt really align with the openapi editor, as the openapi gui is able to handle the allOf.

My code, to give the gist of the issue:

```
UserPermissionsCommon:
      type: object
      additionalProperties: false
      required:
        - permissions
      properties:
        namespace:
          $ref: "#/components/schemas/AllowedUserPermsNamespace"
        permissions:
          $ref: "#/components/schemas/PermissionsV2"

    UserPermissionsPostGetExtra:
      type: object
      additionalProperties: false
      required:
      - name
      properties:
        id:
          type: string
        name:
          type: string
          description: must be the email of the user, as it is on merqube.com. That's the email the oauth resolves to.
        status:
          $ref: "#/components/schemas/Status"

    UserPermissionsPatchExtra:
      type: object
      additionalProperties: false
      required:
      - status
      properties:
        status:
          $ref: "#/components/schemas/Status"

    UserPermissions:
      allOf:
        - $ref: "#/components/schemas/UserPermissionsCommon"
        - $ref: "#/components/schemas/UserPermissionsPostGetExtra"

    UserPermissionsPatch:
      allOf:
        - $ref: "#/components/schemas/UserPermissionsCommon"
        - "#/components/schemas/UserPermissionsPatchExtra"
```

The bottom two Composite definitions fail for Prance - but are fine in Openapi.

What I had to do to get prance to work was:
```
file_dir = path.dirname(path.abspath(__file__))
schema = path.join(file_dir, "openapi.yaml")
SPEC = ResolvingParser(schema).specification
schemas = SPEC["components"]["schemas"]
USER_PERMISSIONS_MANIFEST: Final = _merge([schemas["UserPermissionsCommon"], schemas["UserPermissionsPostGetExtra"]])
```

However, it would be much nicer to do `schemas["UserPermissions"]` and be done with it

**Comment by tommyjcarpenter** [comment] 2022-09-27 14:53
@jfinkhaeuser do you know if there is a current maintainer?

**Comment by jfinkhaeuser** [comment] 2022-09-27 15:26
Well, I transferred it to @RonnyPfannschmidt for reasons of maintaining it, yes.

**Comment by RonnyPfannschmidt** [comment] 2022-09-27 15:41
Im currently on parental leave, im happy to review /merge a pr, getting to it my self may take a while

**Comment by tommyjcarpenter** [comment] 2022-09-28 14:52
@RonnyPfannschmidt ok we will look into making a contribution for this. It will have to have some flag or warning, because as @jfinkhaeuser pointed out, its "only safe when the user says its safe". a merge COULD have a conflict, but in both our and @mafrosis comments, we know that it is safe. 

can you please reopen this issue?

**Comment by RonnyPfannschmidt** [comment] 2023-02-22 11:43
closing again, happy to reopen when a mr comes in

**Closed by RonnyPfannschmidt** 2023-02-22 11:43 UTC
Labels: enhancement, wontfix
